FROM eclipse-temurin:25-jdk-alpine@sha256:d3f9f60ad2040582239e2977ee753d598787d8b064ca39a8e131860165dd81fb AS build

# Set working directory
WORKDIR /usr/app

# Copy only the necessary files for dependency resolution
COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle build.gradle
COPY settings.gradle settings.gradle
COPY src src

# Grant execution rights and build the application
RUN chmod +x ./gradlew && ./gradlew build --no-daemon

## Use a smaller JRE image for the runtime
FROM eclipse-temurin:25-jre-alpine@sha256:5fcc27581b238efbfda93da3a103f59e0b5691fe522a7ac03fe8057b0819c888 AS runtime

# Create the application directory
RUN mkdir /app

# Copy the JAR from the build stage
COPY --from=build /usr/app/build/libs/*.jar /app/app.jar

# Expose the application's port
EXPOSE 8080

# Define the command to run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
