POST http://localhost:8080/api/observations/
Content-Type: application/json


{
    "source": "ZIB",
    "codeListCode": "ZIB001",
    "code": "271636001",
    "displayValue": "Polsslag regelmatig",
    "longDescription": "The long description is necessary",
    "fromDate": "2019-01-01",
    "toDate": "",
    "sortingPriority": 1
}